/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.BarangDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Barang;

/**
 *
 * @author yooson
 */
public class CariBarangDialog extends javax.swing.JDialog {
    private final BarangDAO barangDAO = new BarangDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CariBarangDialog.class.getName());
    
    
    // Variabel statis untuk menampung data barang terpilih
    public static String idBarangTerpilih = "";
    public static String namaBarangTerpilih = "";
    public static double hargaBeliTerpilih = 0;
    public static double hargaJualTerpilih = 0; // Tambahkan ini!
    public static boolean isSelected = false;
    public static int stokBarangTerpilih = 0;

    /**
     * Creates new form CariBarangDialog
     */
    public CariBarangDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadTableData();
        setLocationRelativeTo(parent); // Posisikan di tengah layar induk
        setTitle("Pilih Data Barang");
    }
    
    private void loadTableData() {
        String[] header = {"Kode Barang", "Nama Barang", "Harga Beli", "Harga Jual", "Stok"};
        DefaultTableModel model = new DefaultTableModel(null, header) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tbl_barang.setModel(model);
        
        List<Barang> list = barangDAO.getAllBarang();
        for (Barang b : list) {
            Object[] row = { 
                b.getIdBarang(), 
                b.getNamaBrg(), 
                b.getHargaBeli(), 
                b.getHargaJual(),
                b.getStok() // Nilai stok aman dimasukkan ke kolom indeks ke-4
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
            if (evt.getClickCount() == 2) {
            int row = tbl_barang.getSelectedRow();
            if (row != -1) {
                idBarangTerpilih = tbl_barang.getValueAt(row, 0).toString();
                namaBarangTerpilih = tbl_barang.getValueAt(row, 1).toString();
                hargaBeliTerpilih = Double.parseDouble(tbl_barang.getValueAt(row, 2).toString());
                hargaJualTerpilih = Double.parseDouble(tbl_barang.getValueAt(row, 3).toString());
                stokBarangTerpilih = Integer.parseInt(tbl_barang.getValueAt(row, 4).toString()); // Rekam stok asli
                
                isSelected = true;
                this.dispose(); 
            }
        }
     
    }//GEN-LAST:event_tbl_barangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CariBarangDialog dialog = new CariBarangDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
