/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.User;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author yooson
 */
public class mainFrame extends javax.swing.JFrame {
    private User loggedInUser;
    private CardLayout cardLayout;
    private DashboardPanel panelDashboard;
    private BarangPanel panelBarang;
    private supplierPanel panelSupplier;
    private transaksimasukPanel panelMasuk;
    private transaksikeluarPanel panelKeluar;
    private reportPanel panelReport;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());

    /**
     * Creates new form mainFrame
     */
        public mainFrame(User user) {
        this.loggedInUser = user;
        initComponents();
        
// 1. Tampilkan informasi user di header
        lb_user.setText("User: " + loggedInUser.getNamaUser() + " (" + loggedInUser.getNamaRole() + ")");
        
        // 2. Ambil kontrol CardLayout dari pn_content
        cardLayout = (CardLayout) pn_content.getLayout();
        
        // 3. Inisialisasi objek semua panel
        panelDashboard = new DashboardPanel();
        panelBarang = new BarangPanel();
        panelSupplier = new supplierPanel();
        panelMasuk = new transaksimasukPanel();
        panelKeluar = new transaksikeluarPanel();
        panelReport = new reportPanel();
        
        // 4. Masukkan semua panel ke dalam kontainer pn_content dengan kata kunci unik
        pn_content.add(panelDashboard, "pnl_dashboard");
        pn_content.add(panelBarang, "pnl_barang");
        pn_content.add(panelSupplier, "pnl_supplier");
        pn_content.add(panelMasuk, "pnl_masuk");
        pn_content.add(panelKeluar, "pnl_keluar");
        pn_content.add(panelReport, "pnl_report");
        
        // 5. Set halaman pertama yang otomatis muncul saat login: Dashboard
        showPanel("pnl_dashboard");
        
        // Atur posisi frame di tengah dan layar penuh
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }
        
        private void showPanel(String panelKey) {
        cardLayout.show(pn_content, panelKey);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_barang = new javax.swing.JButton();
        btn_supplier = new javax.swing.JButton();
        btn_transaksimasuk = new javax.swing.JButton();
        btn_transaksikeluar = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        pn_header = new javax.swing.JPanel();
        lb_user = new javax.swing.JLabel();
        lb_tanggal = new javax.swing.JLabel();
        pn_content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_Sidebar.setBackground(new java.awt.Color(153, 153, 255));
        pn_Sidebar.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("jLabel1");
        pn_Sidebar.add(jLabel1);

        btn_dashboard.setText("Dashboard");
        btn_dashboard.addActionListener(this::btn_dashboardActionPerformed);
        pn_Sidebar.add(btn_dashboard);

        btn_barang.setText("Barang");
        btn_barang.addActionListener(this::btn_barangActionPerformed);
        pn_Sidebar.add(btn_barang);

        btn_supplier.setText("Supplier");
        btn_supplier.addActionListener(this::btn_supplierActionPerformed);
        pn_Sidebar.add(btn_supplier);

        btn_transaksimasuk.setText("Transaksi Masuk");
        btn_transaksimasuk.addActionListener(this::btn_transaksimasukActionPerformed);
        pn_Sidebar.add(btn_transaksimasuk);

        btn_transaksikeluar.setText("Transaksi Keluar");
        btn_transaksikeluar.addActionListener(this::btn_transaksikeluarActionPerformed);
        pn_Sidebar.add(btn_transaksikeluar);

        btn_laporan.setText("Laporan");
        btn_laporan.addActionListener(this::btn_laporanActionPerformed);
        pn_Sidebar.add(btn_laporan);

        btn_logout.setText("Logout");
        btn_logout.addActionListener(this::btn_logoutActionPerformed);
        pn_Sidebar.add(btn_logout);

        getContentPane().add(pn_Sidebar, java.awt.BorderLayout.LINE_START);

        pn_header.setBackground(new java.awt.Color(255, 255, 255));

        lb_user.setText("lb_user");

        lb_tanggal.setText("lb_waktu");

        javax.swing.GroupLayout pn_headerLayout = new javax.swing.GroupLayout(pn_header);
        pn_header.setLayout(pn_headerLayout);
        pn_headerLayout.setHorizontalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_headerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lb_user, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(lb_tanggal)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        pn_headerLayout.setVerticalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_headerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_user)
                    .addComponent(lb_tanggal))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(pn_header, java.awt.BorderLayout.PAGE_START);

        pn_content.setLayout(new java.awt.CardLayout());
        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        showPanel("pnl_dashboard");
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barangActionPerformed
        showPanel("pnl_barang");
    }//GEN-LAST:event_btn_barangActionPerformed

    private void btn_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supplierActionPerformed
        showPanel("pnl_supplier");
    }//GEN-LAST:event_btn_supplierActionPerformed

    private void btn_transaksimasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksimasukActionPerformed
        showPanel("pnl_masuk");
    }//GEN-LAST:event_btn_transaksimasukActionPerformed

    private void btn_transaksikeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksikeluarActionPerformed
        showPanel("pnl_keluar");
    }//GEN-LAST:event_btn_transaksikeluarActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        showPanel("pnl_report");
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // Kembali ke form login
    new loginFrame().setVisible(true);
    this.dispose(); // Tutup mainFrame
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_barang;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_supplier;
    private javax.swing.JButton btn_transaksikeluar;
    private javax.swing.JButton btn_transaksimasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_tanggal;
    private javax.swing.JLabel lb_user;
    private javax.swing.JPanel pn_Sidebar;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_header;
    // End of variables declaration//GEN-END:variables
}
