/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.databaseConnection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author yooson
 */
public class reportPanel extends javax.swing.JPanel {
    private java.sql.Connection conn;
    /**
     * Creates new form reportPanel
     */
    public reportPanel() {
        initComponents();
        // isi koneksi: Panggil method static dari config.databaseConnection
        conn = databaseConnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Report = new javax.swing.JLabel();
        Barang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Supplier = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        TM = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        TK = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        btnCetakBrg = new javax.swing.JToggleButton();
        btnCtkSupp = new javax.swing.JToggleButton();
        btnCtkMsk = new javax.swing.JToggleButton();
        btnCtkKlr = new javax.swing.JToggleButton();

        Report.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Report.setText("Report View");

        Barang.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Barang.setText("Barang");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        jTable1.setMinimumSize(new java.awt.Dimension(60, 150));
        jTable1.setPreferredSize(new java.awt.Dimension(300, 150));
        jScrollPane1.setViewportView(jTable1);

        Supplier.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Supplier.setText("Supplier");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        jTable5.setMinimumSize(new java.awt.Dimension(60, 150));
        jTable5.setPreferredSize(new java.awt.Dimension(300, 150));
        jScrollPane5.setViewportView(jTable5);

        TM.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        TM.setText("Barang Masuk");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable6.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        jTable6.setMinimumSize(new java.awt.Dimension(60, 150));
        jTable6.setPreferredSize(new java.awt.Dimension(300, 150));
        jScrollPane6.setViewportView(jTable6);

        TK.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        TK.setText("Barang Keluar");

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable7.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        jTable7.setMinimumSize(new java.awt.Dimension(60, 150));
        jTable7.setPreferredSize(new java.awt.Dimension(300, 150));
        jScrollPane7.setViewportView(jTable7);

        btnCetakBrg.setText("Cetak");
        btnCetakBrg.addActionListener(this::btnCetakBrgActionPerformed);

        btnCtkSupp.setText("Cetak");
        btnCtkSupp.addActionListener(this::btnCtkSuppActionPerformed);

        btnCtkMsk.setText("Cetak");
        btnCtkMsk.addActionListener(this::btnCtkMskActionPerformed);

        btnCtkKlr.setText("Cetak");
        btnCtkKlr.addActionListener(this::btnCtkKlrActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TK)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Report)
                            .addComponent(Barang)
                            .addComponent(Supplier)
                            .addComponent(TM))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCetakBrg)
                            .addComponent(btnCtkSupp)
                            .addComponent(btnCtkMsk)
                            .addComponent(btnCtkKlr))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Report)
                .addGap(59, 59, 59)
                .addComponent(Barang)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetakBrg))
                .addGap(18, 18, 18)
                .addComponent(Supplier)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCtkSupp))
                .addGap(18, 18, 18)
                .addComponent(TM)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCtkMsk))
                .addGap(18, 18, 18)
                .addComponent(TK)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCtkKlr))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakBrgActionPerformed
        eksekusiCetak("/report/barang.jrxml", "barang.jrxml");
    }//GEN-LAST:event_btnCetakBrgActionPerformed

    private void btnCtkSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtkSuppActionPerformed
        eksekusiCetak("/report/supplier.jrxml", "barang.jrxml");
    }//GEN-LAST:event_btnCtkSuppActionPerformed

    private void btnCtkMskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtkMskActionPerformed
        eksekusiCetak("/report/masuk.jrxml", "barang.jrxml");
    }//GEN-LAST:event_btnCtkMskActionPerformed

    private void btnCtkKlrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtkKlrActionPerformed
        eksekusiCetak("/report/keluar.jrxml", "barang.jrxml");
    }//GEN-LAST:event_btnCtkKlrActionPerformed


    
    //METHOD PEMBANTU AGAR KODE TIDAK BERULANG-ULANG
    private void eksekusiCetak(String resourcePath, String fileName) {
        try {
            if (conn == null || conn.isClosed()) {
                conn = databaseConnection.getConnection();
            }

            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Gagal mencetak: Koneksi ke database aktif tidak ditemukan.");
                return;
            }

            // Membaca file mentah .jrxml (Sangat aman untuk menangani Jasper Studio versi 7)
            java.io.InputStream reportStream = getClass().getResourceAsStream(resourcePath);

            if (reportStream == null) {
                JOptionPane.showMessageDialog(this, "File '" + fileName + "' tidak ditemukan di folder src/main/java/view/ !\n"
                        + "Pastikan file mentah .jrxml hasil desain sudah ditaruh di folder tersebut.");
                return;
            }

            // Compile otomatis file .jrxml secara realtime
            JasperReport jasperReport = JasperCompileManager.compileReport(reportStream);
            HashMap<String, Object> parameters = new HashMap<>();

            JasperPrint print = JasperFillManager.fillReport(jasperReport, parameters, conn);
            JasperViewer.viewReport(print, false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal cetak berkas " + fileName + ":\n" + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barang;
    private javax.swing.JLabel Report;
    private javax.swing.JLabel Supplier;
    private javax.swing.JLabel TK;
    private javax.swing.JLabel TM;
    private javax.swing.JToggleButton btnCetakBrg;
    private javax.swing.JToggleButton btnCtkKlr;
    private javax.swing.JToggleButton btnCtkMsk;
    private javax.swing.JToggleButton btnCtkSupp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    // End of variables declaration//GEN-END:variables
}
