/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author yooson
 */
public class transaksimasukPanel extends javax.swing.JPanel {

    /**
     * Creates new form transaksimasukPanel
     */
    public transaksimasukPanel() {
        initComponents();
        transaksiController = new controller.TransaksiController();

    // Simulasi mengambil data user admin yang login (Nanti saat integrasi penuh, 
    // objek User ini bisa dilempar dari mainFrame saat inisialisasi panel)
    userAktif = new model.User("USR001", 2, "Ach Fauzi", "admin", "admin123");

    // Siapkan data awal transaksi masuk
    transaksiController.prepareNewTransaction(this, userAktif);
    }
    
    // Sediakan getter agar controller bisa mengakses komponen visual panel ini
    public javax.swing.JTextField getTxtNoPO() { return txt_noPo; }
    public javax.swing.JTextField getTxtTanggal() { return txt_tanggalPo; }
    public javax.swing.JTextField getTxtPetugas() { return txt_petugas; }
    public javax.swing.JComboBox<String> getCbSupplier() { return combo_supplier; }
    public javax.swing.JTextField getTxtPilihBarang() { return txt_pilihbarang; }
    public javax.swing.JTextField getTxtHargaBeli() { return txt_hargabeli; }
    public javax.swing.JTextField getTxtQty() { return txt_qty; }
    public javax.swing.JTable getTblDetailPO() { return tbl_keranjang; }
    public javax.swing.JButton getBtnTambah() { return btn_keranjang; }
    public javax.swing.JButton getBtnSimpan() { return btn_simpan; }
    public javax.swing.JButton getBtnHapus() { return btn_hapus; }
    public javax.swing.JButton getBtnCariBarang() { return btn_caribarang; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_noPo = new javax.swing.JTextField();
        txt_tanggalPo = new javax.swing.JTextField();
        txt_petugas = new javax.swing.JTextField();
        combo_supplier = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_pilihbarang = new javax.swing.JTextField();
        txt_hargabeli = new javax.swing.JTextField();
        txt_qty = new javax.swing.JTextField();
        btn_caribarang = new javax.swing.JButton();
        btn_keranjang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_keranjang = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();

        txt_noPo.setEditable(false);
        txt_noPo.setText("No PO");

        txt_tanggalPo.setText("Tanggal");
        txt_tanggalPo.addActionListener(this::txt_tanggalPoActionPerformed);

        txt_petugas.setEditable(false);
        txt_petugas.setText("Petugas");

        combo_supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Pilih Barang");

        jLabel6.setText("Harga Beli");

        jLabel7.setText("Qty");

        btn_caribarang.setText("...");
        btn_caribarang.addActionListener(this::btn_caribarangActionPerformed);

        btn_keranjang.setText("Tambah Keranjang");
        btn_keranjang.addActionListener(this::btn_keranjangActionPerformed);

        tbl_keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_keranjang);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_noPo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tanggalPo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_pilihbarang, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_caribarang))
                            .addComponent(txt_hargabeli)
                            .addComponent(txt_qty)))
                    .addComponent(btn_keranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_noPo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tanggalPo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_pilihbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_caribarang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_hargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_keranjang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus))
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tanggalPoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalPoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalPoActionPerformed

    private void btn_caribarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caribarangActionPerformed
    java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    CariBarangDialog dialog = new CariBarangDialog(parentFrame, true);

    // Set status awal pilihan ke false sebelum dibuka
    CariBarangDialog.isSelected = false;
    dialog.setVisible(true);

    // Jika user sukses melakukan double-click dan memilih barang di dialog
    if (CariBarangDialog.isSelected) {
        // Masukkan data barang terpilih ke kolom inputan transaksi masuk
        txt_pilihbarang.setText(CariBarangDialog.idBarangTerpilih + " - " + CariBarangDialog.namaBarangTerpilih);
        txt_hargabeli.setText(String.valueOf(CariBarangDialog.hargaBeliTerpilih));
        txt_qty.requestFocus(); // Otomatis fokuskan kursor ke kolom Qty
    }
    }//GEN-LAST:event_btn_caribarangActionPerformed

    private void btn_keranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keranjangActionPerformed
        if (CariBarangDialog.isSelected) {
        transaksiController.addItemToCart(this, 
                CariBarangDialog.idBarangTerpilih, 
                CariBarangDialog.namaBarangTerpilih, 
                CariBarangDialog.hargaBeliTerpilih);

        // Reset status dialog pilihan barang kembali ke false setelah sukses masuk keranjang
        CariBarangDialog.isSelected = false;
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan klik tombol (...) untuk memilih barang dulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btn_keranjangActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        transaksiController.removeItemFromCart(this);
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        transaksiController.saveTransaction(this, userAktif);
    }//GEN-LAST:event_btn_simpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caribarang;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keranjang;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> combo_supplier;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_keranjang;
    private javax.swing.JTextField txt_hargabeli;
    private javax.swing.JTextField txt_noPo;
    private javax.swing.JTextField txt_petugas;
    private javax.swing.JTextField txt_pilihbarang;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_tanggalPo;
    // End of variables declaration//GEN-END:variables
private controller.TransaksiController transaksiController;
private model.User userAktif;
}
